---
- hosts: 127.0.0.1
  connection: local
  gather_facts: true
  tasks:
  - name: "Set facts RHEL 7"
    block:
    - set_fact:
        packages:
        - gcc
        - python3-pip
        - python3-devel
        - openssl-devel
        - python3-libselinux
        - docker
        - device-mapper-libs
        - python-virtualenv.noarch   

    - set_fact:
        repos:
          - "rhel-7-server-rpms"
          - "rhel-7-server-optional-rpms"
          - "rhel-7-server-extras-rpms"

    - name: "enable repositories"
      command: "subscription-manager repos --enable={{ item }}"
      loop: "{{ repos }}"
  
    - name: install packages
      yum:
        name: "{{ item }}"
      with_items:
        - "{{ packages }}"
    when: (ansible_distribution == "RedHat") and
          (ansible_distribution_major_version == "7")
